name: Run Playwright Tests - HW19

on:
  push:
    branches: [hw19]
  pull_request:
    branches: [hw19]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: hw19

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: "${{ env.BUILD_FOLDER }}/package-lock.json"

      - name: 📥 Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: 🧩 Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: 🧪 Run tests
        run: npm run test tests/pravda-home.spec.ts
        working-directory: ${{ env.BUILD_FOLDER }}
